export const FETCH_HEROES_INIT = 'FETCH_HEROES_INIT';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
export const FETCH_HEROES_FAIL = 'FETCH_HEROES_FAIL';

export const FETCH_HERO_BY_ID_INIT = 'FETCH_HERO_BY_ID_INIT';
export const FETCH_HERO_BY_ID_FAIL = 'FETCH_HERO_BY_ID_FAIL';
export const FETCH_HERO_BY_ID_SUCCESS = 'FETCH_HERO_BY_ID_SUCCESS';